config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'welcome/home', to: 'welcome#home'
  
  
  resources :accounts
  
  
  
  
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
end

app/models/user.rb
class User < ActiveRecord::Base
#   has_many :accounts
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
# Test in console, user = User.new(...)
# then see that when you hit user.save to move it 
# from memory to db, you get rollback!
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false},
            format: { with: VALID_EMAIL_REGEX }
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end
  
  def new
    @account = Account.new
    # note that after you add this, it still won't show anything
    # need to go back to new.html.erb and fill out the form part so it shows stuff
  end
  
  def edit
    @account = Account.find(params[:id])
    # now create and edit account template under views
    # after that you run it and realize...oh shit, need def update below too
  end
  
  def create
#     render plain: params[:account].inspect
    # ^^ allows us to see that when you hit submit, shit is getting passed through appropriately
    
    # NOW we need to save that - need to whitelist it first, so make private below
    #### OOOOH AND B/C OF VALIDATION MAKE AN IF CLAUSE AROUND ALL THIS SHIT
    @account = Account.new(account_params)
    if @account.save
      # after saving, we need to show something to the user, so let's redirect!
      # do rake routes and see that accounts#show is the right path for:
      flash[:notice] = "Account was successfully created"
      # before doing the next part, just realied, need to work with flash notice, so check out application's erb! (under views -> layout)
      redirect_to account_path(@account)
      # but we still need to build that show action first...whoops
    else
      render :new
    end
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params) #(text) from whitelist method
      flash[:notice] = "Account was successfully updated"
      redirect_to account_path(@account)
    else
      render :edit
    end
  end
  
  # show controller time
  def show
    #notice that the url for the show error is account/id# so...
    @account = Account.find(params[:id])
    # now make your views -> accounts -> show.html.erb
  end
  
  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    flash[:notice] = 'Account was successfully deleted'
    redirect_to accounts_path
  end
  
  private
    def account_params
      params.require(:account).permit(:title, :description)
      #require top level key, then "permit" the params we want - only title and description!
      # only this shit will then be saved per the create action above
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<!-- this is a partial - we use it so we dont have to keep copy and pasting shit across new and edit -->

<div class="row">
  <div class='col-xs-12'>
    <!-- expand across all 12 grid columns of bootstrap-->

    <%= form_for(@account, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <!-- but at first rails dont know this, so you go back to controller and add within the def new-->
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          
        

        <%= f.label :title %>
        </div>
        <div class="col-sm-8">
        
        <!-- added a break - <br/> b/c it was too close together -->
        <%= f.text_field :title, class: "form-control", placeholder: "Email", autofocus: true %>
        <!-- NOTE: CAN YOU CHANGE LABEL WITHOUT FUCKING THIS SHIT UP? -->
    <!-- RESPONSE: I don't think so, pretty sure it has to match db columns we specifed under db folder -->  
         </div>
      </div>
    
    
    
     <div class='form-group'>
        <div class='control-label col-sm-2'>
      
          <%= f.label :description %>
       </div>
        
       <div class="col-sm-8">
        <!-- will be text_area instead of text_field b/c a description needs bigger space -->
          <%= f.text_area :description, class: "form-control", placeholder: "Password", autofocus: true %>
       </div>
     </div>
    
    
    <!-- what else do I need? A SUBMIT BUTTON -->
    <div class='form-group'>
      <div class="col-sm-offset-0.8 col-sm-8">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
    <!-- but if you click it, you see what we need next is a create action-->
          <% end %>
       
    
</div>
</div>
<!-- I don't want to give away my db of passwords
 link_to "Back to Account listings", accounts_path %>
^^ enclose this shit in ruby to reactivate
-->

app/views/accounts/edit.html.erb
<style type="text/css">
       
    html { 
  background:  url(https://static.pexels.com/photos/34435/pexels-photo.jpg) no-repeat center center fixed; 
  background-size: cover;
}
  </style>
<body>

<%= render 'shared/errors', obj: @account %>

<h1 style="font-family:helvetica;"> Edit existing account </h1>
<i><p style="font-family:helvetica;"> NOTE: DO NOT GIVE AWAY AN IMPORTANT PASSWORD, I DO NOT SAFEGUARD HEROKU THE HOST, AND ADMIN MAY HAVE ABILITY TO SEE YOUR SUBMITTED INFORMATION </p>
  </i>

<%= render 'form' %>
  <!-- if this was not in accounts, you need folder/form -->
  <!-- if you named the partial _message then it would be render 'message', etc. -->
</body>

app/views/accounts/index.html.erb
<style type="text/css">
       
    html { 
  background:  url(https://static.pexels.com/photos/34435/pexels-photo.jpg) no-repeat center center fixed; 
  background-size: cover;
}
  </style>
<body>
  <h1 style="font-family:helvetica;"> Listing all Accounts:</h1>
  
  <p style="font-family:helvetica;"> 
  <%= link_to "Create new account", new_account_path %> |
  <%= link_to "Home", welcome_home_path %>
  </p>
  <table>
    <tr> <!--table row then table header -->
      <th>Title</th>
      <th>Description</th>
    </tr>
    <% @accounts.each do |account| %>
    <tr>
      <td><%= account.title %></td>
      <td><%= account.description %></td>
      <td><%= link_to "Edit", edit_account_path(account) %></td>
      <td><%= link_to "Show", account_path(account) %></td>
      <td><%= link_to "Delete", account_path(account), method: :delete, data: {confirm: "Are you sure?"} %> </td>
    </tr>
    <% end %>
  </table>
</body>

app/views/accounts/new.html.erb
<style type="text/css">
       
    html { 
  background:  url(https://static.pexels.com/photos/34435/pexels-photo.jpg) no-repeat center center fixed; 
  background-size: cover;
}
  </style>
<body>

<%= render 'shared/errors', obj: @account %>

<h1 style="font-family:helvetica;">Create your account here</h1>
<!-- now we need to add form tools (guides.rubyonrails.org/form_helpers.html)-->
<!--<p style="font-family:helvetica;"> This will be where the db backend interacts </p>
-->
<i><p style="font-family:helvetica;"> NOTE: DO NOT GIVE AWAY AN IMPORTANT PASSWORD! I DO NOT SAFEGUARD HEROKU THE HOST, AND ADMIN MAY HAVE ABILITY TO SEE YOUR SUBMITTED INFORMATION </p>
  </i>

<%= render 'form' %>
  <!-- if this was not in accounts, you need folder/form -->
</body>

app/views/accounts/show.html.erb
<style type="text/css">
       
    html { 
  background:  url(https://static.pexels.com/photos/34435/pexels-photo.jpg) no-repeat center center fixed; 
  background-size: cover;
}
  </style>
<body>
<h1 style="font-family:helvetica;"> Showing selected account </h1>

<p style="font-family:helvetica;"> Title: <%= @account.title %> </p>

<p style="font-family:helvetica;"> Description: <%= @account.description %> </p>
<%= link_to "Edit this Account", edit_account_path(@account) %> |
<%= link_to "Back to Account listings", accounts_path %>
</body>

app/views/layouts/_footer.html.erb
<div class='container'>
  <footer class='footer'>
  <small>
    Copyright &copy; Brandebot 2017 
    </small>

  </footer>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <!-- make it -default to trigger transparent effect -->
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- no longer need this due to ruby code below: -->
      <!-- <a class="navbar-brand" id="logo" href="/">BITCHCOIN</a> -->
      <%= link_to "BITCHCOIN", root_path, class: "navbar-brand", id: "logo" %>
    </div>

   
      <ul class="nav navbar-nav navbar-left">
        <li><a href="#">Login</a></li>
        <!--
        <li><a href="/accounts/new">Create an Account</a></li>
        -->
         <li><%= link_to "Create an Account", new_account_path %></li> 
          </ul>
        </li>
      </ul>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalletApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  
  <!-- BOOTSTRAP FOR HEROKU: if I drop these 
   following two lines, I get my transprency back 
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> </script>
 -->
  </head>
<body>
<!-- this is the ultimate wrapper file - anything put in here will display on every page -->
<% flash.each do |name, msg| %>
  <ul>
    <li> <%= msg %></li>
  </ul>
  <% end %>
  <!-- Because this wrapper will appear on all pages, its a good place to build a nav bar etc. -->
  <%= render 'layouts/navigation' %>
  <div class= "container">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<!-- how about a flash notice if we hit the else clause for bombing validation?-->
<% if  obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-1">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this account from being created:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wallet2.0</title>
  <meta name="author" content="Brandebot">
  <meta name="description" content="A wallet creation">
  <meta name="keywords" content="wallet,cryptocurrency">
  <style type="text/css">
       
    html { 
      background:  url(http://upload.wikimedia.org/wikipedia/commons/d/dd/Muybridge_race_horse_animated.gif) no-repeat center center fixed; 
      background-size: cover;
    }
    
    
    h1 {
      color: grey;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	    font-size: 34px;
	    font-style: normal;
	    font-variant: normal;
	    font-weight: 500;
	    line-height: 26px;
}
		   h3 {
      color: white;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
    
    
  </style>
  </head>

    <!-- Primary buttons -->
	<!-- oh btw I dropped the <body> tag here -->
<!-- <a class="button button-primary" href="#">Anchor button</a> -->
<div class='mainBody'>
	

 
  <h1 id="myTitle"> Welcome to your new wallet </h1>


	</div>

</html>